const { USER_ROLES, VENDOR_TIERS, PERMISSION_SCOPES, ACCOUNT_STATUSES } = require("./roles");
const {
  BOOKING_STATUSES,
  BOOKING_STATUS_LIST,
  VALID_TRANSITIONS,
  CONVERSATION_STATUSES,
  PAYMENT_STATUSES,
  TRANSACTION_TYPES,
} = require("./statuses");
const { ERROR_MESSAGES, SUCCESS_MESSAGES } = require("./messages");

module.exports = {
  // Roles
  USER_ROLES,
  VENDOR_TIERS,
  PERMISSION_SCOPES,
  ACCOUNT_STATUSES,

  // Statuses
  BOOKING_STATUSES,
  BOOKING_STATUS_LIST,
  VALID_TRANSITIONS,
  CONVERSATION_STATUSES,
  PAYMENT_STATUSES,
  TRANSACTION_TYPES,

  // Messages
  ERROR_MESSAGES,
  SUCCESS_MESSAGES,
};
