const BOOKING_STATUSES = {
  DRAFT: "draft",
  REQUESTED: "requested",
  VENDOR_ACCEPTED: "vendor_accepted",
  VENDOR_DECLINED: "vendor_declined",
  PAYMENT_PENDING: "payment_pending",
  CONFIRMED: "confirmed",
  IN_PROGRESS: "in_progress",
  COMPLETED: "completed",
  CANCELLED_BY_USER: "cancelled_by_user",
  CANCELLED_BY_VENDOR: "cancelled_by_vendor",
  REFUND_PENDING: "refund_pending",
  REFUNDED: "refunded",
  DISPUTED: "disputed",
  RESOLVED: "resolved",
  EXPIRED: "expired",
  CLOSED: "closed",
};

const BOOKING_STATUS_LIST = Object.values(BOOKING_STATUSES);

const VALID_TRANSITIONS = {
  [BOOKING_STATUSES.DRAFT]: [BOOKING_STATUSES.REQUESTED],
  [BOOKING_STATUSES.REQUESTED]: [
    BOOKING_STATUSES.VENDOR_ACCEPTED,
    BOOKING_STATUSES.VENDOR_DECLINED,
    BOOKING_STATUSES.EXPIRED,
    BOOKING_STATUSES.CANCELLED_BY_USER,
  ],
  [BOOKING_STATUSES.VENDOR_ACCEPTED]: [
    BOOKING_STATUSES.PAYMENT_PENDING,
    BOOKING_STATUSES.CANCELLED_BY_USER,
    BOOKING_STATUSES.CANCELLED_BY_VENDOR,
  ],
  [BOOKING_STATUSES.VENDOR_DECLINED]: [BOOKING_STATUSES.CLOSED],
  [BOOKING_STATUSES.PAYMENT_PENDING]: [
    BOOKING_STATUSES.CONFIRMED,
    BOOKING_STATUSES.EXPIRED,
    BOOKING_STATUSES.CANCELLED_BY_USER,
  ],
  [BOOKING_STATUSES.CONFIRMED]: [
    BOOKING_STATUSES.IN_PROGRESS,
    BOOKING_STATUSES.CANCELLED_BY_USER,
    BOOKING_STATUSES.CANCELLED_BY_VENDOR,
  ],
  [BOOKING_STATUSES.IN_PROGRESS]: [
    BOOKING_STATUSES.COMPLETED,
    BOOKING_STATUSES.DISPUTED,
  ],
  [BOOKING_STATUSES.COMPLETED]: [
    BOOKING_STATUSES.CLOSED,
    BOOKING_STATUSES.DISPUTED,
  ],
  [BOOKING_STATUSES.CANCELLED_BY_USER]: [
    BOOKING_STATUSES.REFUND_PENDING,
    BOOKING_STATUSES.CLOSED,
  ],
  [BOOKING_STATUSES.CANCELLED_BY_VENDOR]: [
    BOOKING_STATUSES.REFUND_PENDING,
    BOOKING_STATUSES.CLOSED,
  ],
  [BOOKING_STATUSES.REFUND_PENDING]: [BOOKING_STATUSES.REFUNDED],
  [BOOKING_STATUSES.REFUNDED]: [BOOKING_STATUSES.CLOSED],
  [BOOKING_STATUSES.DISPUTED]: [BOOKING_STATUSES.RESOLVED],
  [BOOKING_STATUSES.RESOLVED]: [BOOKING_STATUSES.CLOSED],
  [BOOKING_STATUSES.EXPIRED]: [BOOKING_STATUSES.CLOSED],
  [BOOKING_STATUSES.CLOSED]: [],
};

const CONVERSATION_STATUSES = {
  ACTIVE: "active",
  AGREED: "agreed",
  BOOKING_CREATED: "booking_created",
  CLOSED: "closed",
};

const PAYMENT_STATUSES = {
  PENDING: "pending",
  PARTIAL: "partial",
  COMPLETED: "completed",
  REFUNDED: "refunded",
  FAILED: "failed",
};

const TRANSACTION_TYPES = {
  PAYMENT: "payment",
  REFUND: "refund",
};

module.exports = {
  BOOKING_STATUSES,
  BOOKING_STATUS_LIST,
  VALID_TRANSITIONS,
  CONVERSATION_STATUSES,
  PAYMENT_STATUSES,
  TRANSACTION_TYPES,
};
